programingJournal/journalApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'journalApp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.index, name='index'),
    url(r'^/saveNewDay',views.saveNewDay, name='saveNewDay')
]

programingJournal/programingJournal/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('journalApp.urls')),
    url(r'^admin/', admin.site.urls),
]

programingJournal/journalApp/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
# Create your models here.

@python_2_unicode_compatible
class Entry(models.Model):
    creation_date = models.DateTimeField('date Created')
    page_name = models.CharField(max_length=64)
    line_number = models.CharField(max_length=5)
    working_on = models.CharField(max_length=255)
    goals = models.CharField(max_length=255)
    def __str__(self):
        return str(self.creation_date.strftime("%b %d %Y %H:%M"))

programingJournal/journalApp/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.views.generic import DetailView
from .models import Entry
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from itertools import chain
import pdb
# Create your views here.

def index(request, pk = -1):
    entry_id = pk
    if entry_id != -1:
        newest_entry = get_object_or_404(Entry, pk=entry_id)
    else:
        newest_entry = Entry.objects.latest('creation_date')

    all_entries = Entry.objects.all()
    context = { 'newest_entry' : newest_entry,
                'all_entries' : all_entries
    }
    return render(request, 'journalApp/index.html',context)

def saveNewDay(request):
    entry = Entry()
    entry.creation_date = timezone.now()
    entry.page_name = request.GET['curPage']
    entry.line_number = request.GET['lineNumber']
    entry.working_on = request.GET['currentThoughts']
    entry.goals = request.GET['goals']
    entry.save()
    return HttpResponseRedirect('/')

programingJournal/journalApp/templates/journalApp/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'journalApp/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

<div class="inspiration centerMe">
    <h1>

        “Focus on being productive instead of busy.”
    </h1>
    <h2>
        ~ Tim Ferriss
    </h2>
</div>

<div class="content">
    <div id="lastEntry">
        <div class="centerHorz">
            <h2>Last Work Session</h2>
            <div class="entry">Date: <span class="journalText">{{newest_entry}}</span></div>
            <div class="entry">Page Name: <span class="journalText">{{newest_entry.page_name}}</span></div>
            <div class="entry">Line Number: <span class="journalText">{{newest_entry.line_number}}</span></div>
        </div>
        <div class="entry">What I was working on:</div>
        <div class="entry journalText" id="prevSession">
            {{newest_entry.working_on}}
        </div>
        <div class="entry">What I am going to get down now:</div>
        <div class="entry journalText" id="curGoals">
            {{newest_entry.goals}}
        </div>
    </div>
    <div id="buttons" class="clearfix">
        <button onclick="createNewEntry()">New Entry</button>
	    <button onclick="viewPreviusEntries()">View Entry</button>
    </div>
    <form id="newEntry" style="display:none" action="{% url 'journalApp:saveNewDay' %}" >
        <h2 class="centerHorz">Save your session</h2>
        <div class="inputTop">
            Current Page Name:
        </div>
        <div class="inputBottom">
            <input type="text" maxlength="64" placeholder="index.php" id="curPage" name="curPage" ></input>
        </div>
        <div class="inputTop">
            Current Line Number:
        </div>
        <div class="inputBottom">
            <input type="text" maxlength="5" placeholder="78" name="lineNumber"></input>
        </div>
        <div class="inputTop">
            What I was working on:
        </div>
        <div class="inputBottom">
            <textarea rows="4" cols="60" placeholder="Current Thoughts..." name="currentThoughts"></textarea>
        </div>
        <div class="inputTop">
            Goals for next time:
        </div>
        <div class="inputBottom">
            <textarea rowss="4" cols="60" placeholder="I am going to finish..." name = "goals"></textarea>
        </div>
        <div class="clearfix">
            <button type="submit">Save</button>
        </div>
    </form>
	<div id="previousEntries" style="display:none">
		<h2>Previous Entries</h2>
        <div class="clearfix">
    		{% for entry in all_entries %}
                <a href = "/{{ entry.id}}" >{{entry}}</a>
    		{% endfor %}
        </div>
	</div>
</div>
<script>
$(function(){
    $("#newEntry").hide();
	$("#previousEntries").hide();
});

function viewPreviusEntries(){
	$("#newEntry").slideUp("fast",function(){
	    $('#previousEntries').slideDown();
	});
}

function createNewEntry(){
	$("#previousEntries").slideUp("fast",function(){
	    $('#newEntry').slideDown();
	});
    $('#curPage').focus();
    /* adapted from: http://stackoverflow.com/questions/6682451/animate-scroll-to-id-on-page-load*/
    $("html, body").animate({ scrollTop: $('#curPage').offset().top }, 1000);
}
</script>